package com.example.demo3.controller;

import com.example.demo3.model.Aluno;
import com.example.demo3.repository.AlunoRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.view.RedirectView;

@Controller
@RequestMapping("/")
public class AlunoController {

	@Autowired // Which is auto-generated by Spring, we will use it to handle the data
	private AlunoRepository alunoRepository;

	@GetMapping(path = "/index")
	public String showPageNow(Model model, @RequestParam(defaultValue = "0") int page) {
		model.addAttribute("alunos", alunoRepository.findAll());
		return "index";
	}

	@GetMapping(path = "/")
	public String showPage(Model model) {
		model.addAttribute("alunos", alunoRepository.findAll());
		return "index";
	}

	@GetMapping(path = "/all")
	public @ResponseBody RedirectView Aluno(Model model) {
		model.addAttribute("alunos", alunoRepository.findAll());
		// return "index";
		// return new ModelAndView("forward:/index", model);
		return new RedirectView("index");
	}

	@PostMapping(path = "/add")
	public @ResponseBody RedirectView addNewAluno(@RequestParam String firstName, @RequestParam String lastName) {

		Aluno a = new Aluno();
		a.setFirstName(firstName);
		a.setLastName(lastName);
		alunoRepository.save(a);
		// return "redirect:/";
		// return "redirect:/index";
		return new RedirectView("index");
	}

	@PostMapping(path = "/delete")
	public @ResponseBody RedirectView delAluno(Integer id) {
		alunoRepository.deleteById(id);
		// return "redirect:/index";
		return new RedirectView("index");

	}

}